/**
 * get-cookies
 *
 * Exports all cookies for the current site as a cookies.txt file
 * in standard Netscape format — compatible with curl, wget, yt-dlp,
 * Python's MozillaCookieJar, and more.
 *
 * Privacy: cookies never leave your device. The file is saved locally.
 *
 * Usage:
 *   1. Navigate to the site whose cookies you want (e.g. youtube.com)
 *   2. Click "Get Data" — collects all cookies for that domain
 *   3. Click "Run CD"  — downloads cookies.txt to your computer
 */

/**
 * Format a single cookie as a Netscape cookies.txt line.
 *
 * Netscape format (tab-separated):
 *   domain  includeSubdomains  path  secure  expiry  name  value
 *
 * @param {Object} cookie - Full cookie object from chrome.cookies
 * @param {string} fallbackDomain - Used when cookie.domain is missing
 * @returns {string}
 */
function formatNetscapeLine(cookie, fallbackDomain) {
  var domain = cookie.domain || fallbackDomain || '';

  // Netscape flag: TRUE when domain starts with "." (subdomains can read it)
  var includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';

  // Ensure domain has a leading dot for subdomains (standard behaviour)
  if (domain && !domain.startsWith('.')) {
    domain = '.' + domain;
  }

  var path = cookie.path || '/';
  var secure = cookie.secure ? 'TRUE' : 'FALSE';

  // Expiry: 0 for session cookies, Unix timestamp otherwise
  var expiry = (!cookie.session && cookie.expirationDate)
    ? Math.floor(cookie.expirationDate)
    : 0;

  var name = cookie.name || '';
  var value = cookie.value || '';

  return [domain, includeSubdomains, path, secure, expiry, name, value].join('\t');
}

/**
 * Build the full Netscape cookies.txt content.
 *
 * @param {Array} cookies - Array of cookie objects
 * @param {string} domain - Page domain (used as fallback)
 * @returns {string}
 */
function buildNetscapeContent(cookies, domain) {
  var lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by CD-Driver get-cookies',
    '# This file is for local use only. Do not share it.',
    '# Compatible with curl, wget, yt-dlp, Python MozillaCookieJar.',
    ''
  ];

  cookies.forEach(function (cookie) {
    lines.push(formatNetscapeLine(cookie, domain));
  });

  lines.push(''); // trailing newline
  return lines.join('\n');
}

/**
 * Called when the user clicks "Get Data".
 * Collects all cookies for the current site via useCookies:true context.
 *
 * @param {string} currentUrl - Active tab URL
 * @param {Object} [context]  - Injected by core: { cookies: [...] }
 */
function DataCollector(currentUrl, context) {
  var result = {
    pageUrl: currentUrl || '',
    domain: '',
    cookies: [],
    message: ''
  };

  if (!currentUrl) {
    result.error = 'No URL provided.';
    return result;
  }

  try {
    result.domain = new URL(currentUrl).hostname;
  } catch (e) {
    result.error = 'Invalid URL: ' + currentUrl;
    return result;
  }

  var cookies = (context && Array.isArray(context.cookies)) ? context.cookies : [];
  result.cookies = cookies;

  if (cookies.length === 0) {
    result.message = [
      'Domain: ' + result.domain,
      'Cookies found: 0',
      '',
      'No cookies found. Make sure you are logged into the site.'
    ].join('\n');
  } else {
    result.message = [
      'Domain: ' + result.domain,
      'Cookies found: ' + cookies.length,
      '',
      'Click "Run CD" to download cookies.txt'
    ].join('\n');
  }

  return result;
}

/**
 * Called when the user clicks "Run CD".
 * Generates cookies.txt in Netscape format and downloads it.
 *
 * @param {Object} data - Return value from DataCollector()
 */
function Run(data) {
  if (!data) {
    return { success: false, error: 'No data. Click "Get Data" first.' };
  }

  if (data.error) {
    return { success: false, error: data.error };
  }

  if (!data.cookies || data.cookies.length === 0) {
    return {
      success: false,
      error: 'No cookies to export. Make sure you are logged into ' + (data.domain || 'the site') + '.'
    };
  }

  var content = buildNetscapeContent(data.cookies, data.domain);

  // Encode as a data URL so chrome.downloads can save it as a local file.
  // encodeURIComponent handles all Unicode/special characters safely.
  var dataUrl = 'data:text/plain;charset=utf-8,' + encodeURIComponent(content);

  var filename = (data.domain || 'cookies').replace(/^\./, '') + '_cookies.txt';

  return {
    success: true,
    action: 'download',
    download: {
      url: dataUrl,
      filename: filename,
      saveAs: true
    },
    message: [
      'Exporting ' + data.cookies.length + ' cookies for ' + data.domain,
      'Format: Netscape cookies.txt',
      'File: ' + filename,
      '',
      'Use with yt-dlp:',
      'yt-dlp --cookies ' + filename + ' <URL>'
    ].join('\n')
  };
}
